### ISSUE TITLE
Sometimes column header stays red after conversion to Date

### ISSUE THREAD

**Issue by gbella** [opendatatrentino/OpenDataRise#102]
e.g., Tariffe e orari impianti a fune/Orari degli impianti stagione invernale 2014-2015
"Apertura dal giorno" converted to Date (End/Start attr).
String converted to datetime but the colour stays red.
See also bug #108 .

**Comment by DavidLeoni** [comment]
Actually the column stays red because some non immidatly visible  dates down the table are the empty string and conversion gives an error in the cell (and this is why the bug is related to #108) . 
So we need:
1) let null/empty string -> Date conversion succeed producing a `null` date.
2) Signal the user the amount  problems in the column with a progress bar, see #130

**Comment by DavidLeoni** [comment]
Fixed in branch-0.3
