### ISSUE TITLE
ODR ocasionally becomes unresponsive in step 4

### ISSUE THREAD

**Issue by gbella** [opendatatrentino/OpenDataRise#182]
I observed it in step 4 but maybe it also happens elsewhere.
The last console output before hanging typically is:
last console output before hanging:
ODR: Odred.afterFetchRows start.
Odred.js (line 1748)
and sometimes also:
GET http://**_CENSORED**_/odr-digiuni/scripts/views/data-table/column-header.html 200 OK 16ms

Digiuni project where it happened: 2172096566346

**Comment by DavidLeoni** [comment]
My greatest fear is we have some kind of deadlock

I'm wondering if the bug #189 somehow disrupted the ui causing strange behaviours. Now at least that one is fixed, let's see how ODR works.

**Comment by DavidLeoni** [comment]
The problem seems caused by `Refine.update()` creating the showBusy panel and not dismissing it, for some reason `Refine.createUpdateFunction` doesn't seem to call all the refresh functions including the one that should dismiss the panel. 'Solved' in dev-0.3 by commenting out panel creation, but needs testing. And if the damned panel appears again,  curse loudly and enter in the browser console:

```
DialogSystem.dismissAll()
```
